name: Standalone Transition UI CI

on:
  pull_request:
    paths:
      - "web/post-restoration-transition-application/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: "./web/post-restoration-transition-application"

jobs:
  standalone-transition-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "standalone-transition-ui"
      working_directory: "./web/post-restoration-transition-application"
      codecov_flag: "postrestorationtransitionapplication"
      node_version: 24
      pnpm_version: 10.0.0
